default:
  image: docker:cli
  services:
    - docker:dind
  before_script:
    - apk add git
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

stages:
  - build

build:job-1:
  stage: build
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  script:
    - docker build -t "$DOCKER_IMAGE_NAME" .
    - echo "docker image $DOCKER_IMAGE_NAME"
    - docker push "$DOCKER_IMAGE_NAME"
    - docker image ls
    - docker rmi "$DOCKER_IMAGE_NAME"
    - docker image ls
  rules:
    - when: manual

build:job-2:
  stage: build
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  script:
    - docker build -t "$DOCKER_IMAGE_NAME" .
    - echo "docker image $DOCKER_IMAGE_NAME"
    - docker push "$DOCKER_IMAGE_NAME"
    - docker image ls
    - docker rmi "$DOCKER_IMAGE_NAME"
    - docker image ls
  rules:
    - if: $CI_COMMIT_TAG
      when: always